version: '3'

services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      - TZ=America/Chicago
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=password
      - IPAM_DATABASE_USER=root
      - IPAM_DATABASE_WEBHOST=%
    restart: always
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    command: >
      sh -c "sed -i '/api_allow_unsafe/s/false/true/' /phpipam/config.dist.php && /start_apache2"
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      - TZ=Europe/London
      - IPAM_DATABASE_HOST=phpipam-mariadb
      - IPAM_DATABASE_PASS=password
      - IPAM_DATABASE_USER=root
      - SCAN_INTERVAL=1h
    restart: always
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
    restart: always
    ports:
    - "3306:3306"
    volumes:
      - phpipam-db-data-x:/var/lib/mysql

volumes:
  phpipam-db-data-x:
  phpipam-logo:
  phpipam-ca:
